name: Input action use

on:
 workflow_dispatch:
  inputs:
    name: 
      description: "Name"
      type: string
      default: "Nikhita"

    age: 
      description: "Age"
      type: number
      required: true
      
jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
       - name: "name-input"
         run: echo "${{ inputs.name }}"

       - name: "age-input"
         run: echo ${{ inputs.age }}
      
         
         
         
         
