name: Input action use

on:
 workflow_dispatch:
  inputs:
    name: 
      description: "Name"
      type: string
      default: "Nikhita"

    age: 
      description: "Age"
      type: number
      required: true

    env: 
      description: "Environment"
      type: choice
      required: true
      options:
        - dev
        - stage
        - production 
        
    married: 
      description: "Is married"
      type: booloean 
 
      
jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
       - name: "name-input"
         run: echo "${{ inputs.name }}"

       - name: "age-input"
         run: echo ${{ inputs.age }}

       - name: "env-input"
         run: echo ${{ inputs.env }}

       - name: "status-input"
         run: echo ${{ inputs.married }}








         
      
         
         
         
         
