name: Input action use

on:
 workflow_dispatch:
  inputs:
    name: 
      description: "Dummy_input"
      type: string
      default: "Happy Birthday"
jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
       - name: "set-input"
         run: echo "${{ inputs.name }}"
      
         
         
         
         
