name: Scheduled Job

on:
  schedule:
    - cron: '*/1 * * * *'   # every 1 minutes
  workflow_dispatch:         # 👈 enables "Run workflow" button
  push:                      # 👈 optional: run when you commit/push
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
